# Download Gradle wrapper and install dependencies.
FROM openjdk:11-jdk-buster as deps

WORKDIR /opt/build
COPY *.kts gradle.properties gradlew* /opt/build/
COPY gradle /opt/build/gradle

# Add or remove '--info' as needed.
RUN ./gradlew installDist --build-cache


# Build project with downloaded Gradle wrapper and cached dependencies.
FROM openjdk:11-jdk-buster as build

WORKDIR /opt/build
COPY --from=deps /root/.gradle /root/.gradle/
COPY . /opt/build/
