version: '3.9'
services:
  frontend:
    build: https://github.com/echo-webkom/echo-web-frontend.git#master
    image: echo-web-frontend:latest
    command: bash -c "yarn start & yarn cypress run --config video=false,screenshotOnRunFailure=false && kill $$!"
    # Don't start tests before backend is up.
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
    ports:
      - '3000:3000'
    environment:
      BACKEND_URL: http://backend:8080
      BEDKOM_KEY: bedkom-passord
      CONTENTFUL_ENVIRONMENT_ID: testing
      # Replace these with real values.
      CONTENTFUL_SPACE_ID: your-space-id-here
      CONTENTFUL_ACCESS_TOKEN: your-access-token-here

  backend:
    build: .
    image: echo-web-backend:latest
    # Don't start backend before database is up.
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - '8080:8080'
    # Check if backend is ready, and insert bedpres for testing.
    healthcheck:
      test: ["CMD-SHELL", "./test_scripts/submit_bedpres -t -x $$WEBKOM_KEY || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DEV: ja
      DATABASE_HOST: database
      BEDKOM_KEY: bedkom-passord
      WEBKOM_KEY: webkom-passord

  database:
    image: postgres:13.2-alpine
    restart: always
    ports:
      - '5432:5432'
    # Check if database is ready.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
