version: '3.9'
services:
  backend-test:
    build:
      context: .
      dockerfile: Dockerfile.test
    image: echo-web-backend-test:latest
    depends_on:
      - database-test
    links:
      - database-test
    ports:
      - '8080:8080'
    command: ./gradlew test --build-cache --no-rebuild --no-daemon
    environment:
      # The value of DEV doesn't matter.
      DEV: ja
      DATABASE_HOST: database-test
      AUTH_KEY: hemmelig

  database-test:
    # Postgres 13.2 is the version Heroku uses.
    image: postgres:13.2-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
