version: '3.9'
services:
  frontend:
    image: '${REGISTRY:-ghcr.io}/echo-webkom/echo-web-frontend:${FRONTEND_TAG:-latest}'
    command: bash -c "yarn start & yarn cypress run --config video=false,screenshotOnRunFailure=false && kill $$!"
    # Don't start tests before backend is up.
    depends_on:
      backend:
        condition: service_healthy
    links:
      - backend
    ports:
      - '3000:3000'
    environment:
      BACKEND_URL: http://backend:8080
      # Value of DEV doesn't matter, only that it's defined.
      DEV: 'yes'
      # Values from .env file.
      SANITY_TOKEN: ${SANITY_TOKEN:?Must specify SANITY_TOKEN in .env file or environment.}
      SANITY_DATASET: ${SANITY_DATASET:?Must specify SANITY_DATASET in .env file or environment.}
      ADMIN_KEY: ${ADMIN_KEY:?Must specify ADMIN_KEY in .env file or environment.}

  backend:
    build:
      context: .
      cache_from:
        - '${REGISTRY:-ghcr.io}/echo-webkom/echo-web-backend:${BACKEND_TAG:-latest-dev}'
    image: '${REGISTRY:-ghcr.io}/echo-webkom/echo-web-backend:${BACKEND_TAG:-latest-dev}'
    # Don't start backend before database is up.
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - '8080:8080'
    # Check if backend is ready, and insert bedpres for testing.
    healthcheck:
      test: ["CMD-SHELL", "./scripts/submit_happening -t -x $$ADMIN_KEY || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      DATABASE_URL: postgres://postgres:password@database/postgres
      # Value of DEV doesn't matter, only that it's defined.
      DEV: 'yes'
      # Values from .env file
      ADMIN_KEY: ${ADMIN_KEY:?Must specify ADMIN_KEY in .env file or environment.}

  database:
    # Postgres 13.6 is the version Heroku uses.
    image: postgres:13.6-alpine
    restart: always
    ports:
      - '5432:5432'
    # Check if database is ready.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
