# Install dependencies with yarn.
# Node 14 is the version Vercel uses.
FROM node:14-alpine as deps

WORKDIR /opt/build
COPY package.json yarn.lock ./
COPY frontend frontend

RUN yarn --frozen-lockfile --ignore-scripts


# Build with Next (no default command).
FROM cypress/base:latest as build

ARG SANITY_DATASET

WORKDIR /opt/build
COPY --from=deps /opt/build/node_modules ./node_modules/
COPY --from=deps /root/.cache /root/.cache/
COPY frontend frontend

RUN yarn build --production
