#!/bin/bash

# Default values
host=http://localhost
port=8080

while getopts zps:x: flag; do
  case "${flag}" in
  z) host=${OPTARG} ;;
  p) port=${OPTARG} ;;
  s) slug=${OPTARG} ;;
  x) secret=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)"
  exit 1
fi

if [ -z ${slug+x} ]; then
  echo "Slug not defined (use -s)"
  exit 1
fi

curl --verbose \
  -X DELETE \
  -H "Authorization: $secret" \
  -H "Connection: close" \
  -H "Content-Type: application/json" \
  -d '{ "slug": "'"$slug"'" }' \
  "$host":"$port"/bedpres
