#!/bin/bash

while getopts p:s:x: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        s) slug=${OPTARG};;
        x) secret=${OPTARG};;
    esac
done

if [ -z ${secret+x} ]; then
    echo "No authorization header specified (use -x)"
    exit 1;
fi

if [ -z ${port+x} ]; then
    echo "Port not defined (use -p)";
    exit 1;
fi

if [ -z ${slug+x} ]; then
    echo "Slug not defined (use -s)";
    exit 1;
else
    curl --verbose \
    -X DELETE \
    -H "Authorization: $secret" \
    http://0.0.0.0:$port/bedpres?slug=$slug;
fi
