#!/bin/bash

while getopts p:e:s:x: flag
do
    case "${flag}" in
        p) port=${OPTARG};;
        e) email=${OPTARG};;
        s) slug=${OPTARG};;
        x) secret=${OPTARG};
    esac
done

if [ -z ${secret+x} ]; then
    echo "No authorization header specified (use -x)."
    exit 1;
fi

if [ -z ${email+x} -a -z ${slug+x} ]; then
    curl --verbose \
    -H "Authorization: $secret" \
    http://localhost:$port/registration
elif [ -z ${slug+x} ]; then
    curl --verbose \
    -H "Authorization: $secret" \
    http://localhost:$port/registration?email=$email
elif [ -z ${email+x} ]; then
    curl --verbose \
    -H "Authorization: $secret" \
    http://localhost:$port/registration?slug=$slug
else
    curl --verbose \
    -H "Authorization: $secret" \
    "http://localhost:$port/registration?email=$email&slug=$slug"
fi
