#!/bin/bash

host=http://echo-web-backend.herokuapp.com

while getopts zp:e:f:l:d:y:s:t: flag
do
    case "${flag}" in
        z) host=http://localhost;;
        p) port=${OPTARG};;
        e) email=${OPTARG};;
        f) firstName=${OPTARG};;
        l) lastName=${OPTARG};;
        d) degree=${OPTARG};;
        y) degree_year=${OPTARG};;
        s) slug=${OPTARG};;
        t) terms=${OPTARG};;
    esac
done

if [ -z ${port+x} ] || [ -z ${email+x} ] || [ -z ${firstName+x} ] || [ -z ${lastName+x} ] || [ -z ${degree+x} ] || [ -z ${degree_year+x} ] || [ -z ${slug+x} ] || [ -z ${terms+x} ] ; then
    echo "Arguments not defined: -p for port, -e for email, -f for firstName, -l for lastName, -d for degree, -y for degree year, -s for slug, -t for terms";
else
    curl --verbose \
    -H "Content-Type: application/json" \
    -H "Connection: close" \
    -d '{ "email": "'${email}'",
          "firstName": "'${firstName}'",
          "lastName": "'${lastName}'",
          "degree": "'${degree}'",
          "degreeYear": '${degree_year}',
          "slug": "'${slug}'",
          "terms": '${terms}' }' \
    $host:$port/registration;
fi
