#!/bin/bash

host=http://echo-web-backend.herokuapp.com

while getopts zp:s:o:r:x: flag; do
  case "${flag}" in
  z) host=http://localhost ;;
  p) port=${OPTARG} ;;
  s) slug=${OPTARG} ;;
  o) spots=${OPTARG} ;;
  r) regdate=${OPTARG} ;;
  x) secret=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)"
  exit 1
fi

if [ -z ${port+x} ]; then
  echo "Port not defined (use -p)"
  exit 1
fi

if [ -z ${slug+x} ] && [ -z ${spots+x} ]; then
  echo "Slugs and spots not defined (use -s and -o)"
  exit 1
elif [ -z ${slug+x} ]; then
  echo "Slug not defined (use -s)"
  exit 1
elif [ -z ${spots+x} ]; then
  echo "Spots not defined (use -o)"
  exit 1
elif [ -z ${regdate+x} ]; then
  echo "RegistrationDate not defined (use -r)"
else
  curl --verbose \
    -X PUT \
    -H "Authorization: $secret" \
    -H "Connection: close" \
    -H "Content-Type: application/json" \
    -d '{ "slug": "'${slug}'", "spots": '${spots}', "registrationDate": "'${regdate}'" }' \
    $host:$port/bedpres
fi
