#!/bin/bash

curl --verbose -X POST \
-H "Content-Type: application/json" \
-d '{ "email": "foo@student.uib.no",
      "firstName": "Test",
      "lastName": "McTest",
      "degree": "DTEK",
      "slug": "generisk-bedriftspresentasjon",
      "terms: true }' \
http://localhost:$1/registration
