#!/bin/bash

# Default values
host=http://localhost
port=8080
user=admin

while getopts zpe:s:x:u:h: flag; do
  case "${flag}" in
  z) host=${OPTARG} ;;
  p) port=${OPTARG} ;;
  e) email=${OPTARG} ;;
  s) slug=${OPTARG} ;;
  x) secret=${OPTARG} ;;
  u) user=${OPTARG} ;;
  h) happening=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)."
  exit 1
fi

if [ -z ${happening+x} ]; then
  echo "Happening type not defined (use -h)."
  exit 1
fi

if [ -z ${email+x} ] && [ -z ${slug+x} ]; then
  curl --verbose \
    -u "$user":"$secret" \
    "$host:$port/registration?type=$happening"
elif [ -z ${slug+x} ]; then
  curl --verbose \
    -u "$user":"$secret" \
    "$host:$port/registration?email=$email&type=$happening"
elif [ -z ${email+x} ]; then
  curl --verbose \
    -u "$user":"$secret" \
    "$host:$port/registration?slug=$slug&type=$happening"
else
  curl --verbose \
    -u "$user":"$secret" \
    "$host:$port/registration?email=$email&slug=$slug&type=$happening"
fi
