#!/bin/bash

# Default values
host="http://localhost"
port="8080"
testing=false
user="webkom"

while getopts zpts:o:r:x:u flag; do
  case "${flag}" in
  z) host=${OPTARG} ;;
  p) port=${OPTARG} ;;
  t) testing=true ;;
  s) slug=${OPTARG} ;;
  o) spots=${OPTARG} ;;
  r) regdate=${OPTARG} ;;
  x) secret=${OPTARG} ;;
  u) user=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)"
  exit 1
fi

if [ "$testing" = true ]; then
  curl --verbose \
    -X PUT \
    -u "$user":"$secret" \
    -H "Connection: close" \
    -H "Content-Type: application/json" \
    -d '{ "slug": "bedriftspresentasjon-med-bekk", "spots": 50, "registrationDate": "2021-05-06T16:46+01:00", "minDegreeYear": 1, "maxDegreeYear": 5 }' \
    "$host":"$port"/bedpres
  exit 0
fi

if [ -z ${slug+x} ]; then
  echo "Slug not defined (use -s)"
  exit 1
fi

if [ -z ${spots+x} ]; then
  echo "Spots not defined (use -o)"
  exit 1
fi

if [ -z ${regdate+x} ]; then
  echo "Registration date not defined (use -r)"
  exit 1
fi

curl --verbose \
  -X PUT \
  -u "$user":"$secret" \
  -H "Connection: close" \
  -H "Content-Type: application/json" \
  -d '{ "slug": "'"${slug}"'", "spots": '"${spots}"', "registrationDate": "'"${regdate}"'", "minDegreeYear": 1, "maxDegreeYear": 5 }' \
  "$host":"$port"/bedpres
