#!/bin/bash

# Default values
host=http://localhost
port=8080
testing=false
user=admin
spotranges="[]"

while getopts zpts:r:x:h: flag; do
  case "${flag}" in
  z) host=${OPTARG} ;;
  p) port=${OPTARG} ;;
  t) testing=true ;;
  s) slug=${OPTARG} ;;
  r) regdate=${OPTARG} ;;
  x) secret=${OPTARG} ;;
  h) happening=${OPTARG} ;;
  o) spotranges=${OPTARG} ;;
  *) echo "Invalid flag." ;;
  esac
done

if [ -z ${secret+x} ]; then
  echo "No authorization header specified (use -x)"
  exit 1
fi

if [ "$testing" = true ]; then
  curl --verbose \
    -X PUT \
    -u "$user":"$secret" \
    -H "Connection: close" \
    -H "Content-Type: application/json" \
    -d '{ "slug": "bedriftspresentasjon-med-bekk", 
          "registrationDate": "2021-05-06T16:46+01:00",
          "spotRanges":
              [
                { 
                   "spots": 30,
                   "minDegreeYear": 1,
                   "maxDegreeYear": 2
                },
                { 
                   "spots": 30,
                   "minDegreeYear": 3,
                   "maxDegreeYear": 5
                }
              ],
          "type": "BEDPRES" }' \
    "$host":"$port"/happening
  curl --verbose \
    -X PUT \
    -u "$user":"$secret" \
    -H "Connection: close" \
    -H "Content-Type: application/json" \
    -d '{ "slug": "fest-med-tilde", 
          "registrationDate": "2021-05-06T16:46+01:00",
          "spotRanges":
              [
                { 
                   "spots": 50,
                   "minDegreeYear": 1,
                   "maxDegreeYear": 5
                }
              ],
          "type": "EVENT" }' \
    "$host":"$port"/happening
  exit 0
fi

if [ -z ${slug+x} ]; then
  echo "Slug not defined (use -s)"
  exit 1
fi

if [ -z ${regdate+x} ]; then
  echo "Registration date not defined (use -r)"
  exit 1
fi

if [ -z ${happening+x} ]; then
  echo "Happening type not defined (use -h)"
  exit 1
fi

curl --verbose \
  -X PUT \
  -u "$user":"$secret" \
  -H "Connection: close" \
  -H "Content-Type: application/json" \
  -d '{ "slug": "'"${slug}"'",
        "registrationDate": "'"${regdate}"'",
        "spotRanges": "'"${spotranges}"'",
        "type": "'"${happening}"'" }' \
  "$host":"$port"/happening
