name: Build CMS
on:
  pull_request:
    branches: [master]
    paths-ignore: ['cms/**']
  merge_group: [checks_requested]

jobs:
  build_cms:
    name: 'Build CMS'
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
