name: Build

on:
  pull_request:
    branches: [develop, master]

jobs:
  gradle_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Build with Gradle & Shadow
        run: ./gradlew shadowJar
