name: Cypress component tests
on:
  pull_request:
    branches: [master]
    paths-ignore: ['frontend/**']

jobs:
  cypress_component_tests:
    name: 'Cypress component tests'
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
