name: Cypress
on:
  pull_request:
    branches: [develop, master]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v2

    - name: Checkout frontend repository
      uses: actions/checkout@v2
      with:
        repository: echo-webkom/echo-web-frontend
        path: frontend
        ref: master

    - name: Build frontend
      run: docker build -t echo-web-frontend:latest frontend

    - name: Set up environment
      run: |
        sed -i 's/your-space-id-here/$CONTENTFUL_SPACE_ID/' $COMPOSE_FILE
        sed -i 's/your-access-token-here/$CONTENTFUL_ACCESS_TOKEN/' $COMPOSE_FILE
        # Remove build context pointing to Git URL, since building
        # from Git URL in Docker Compose doesn't work with GitHub Actions.
        sed -i '4d' $COMPOSE_FILE
      env:
        CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID_TESTING }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_TESTING }}
        CONTENTFUL_ENVIRONMENT_ID: testing
        COMPOSE_FILE: docker-compose.cypress.yaml

    - name: Run Cypress end-to-end tests
      run: ./cypress
