name: Cypress component tests
on:
  pull_request:
    branches: [master]
    paths: ['frontend/**']
  merge_group:
    types: [checks_requested]

jobs:
  cypress_component_tests:
    name: 'Cypress component tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache Cypress binary and yarn dependencies
        uses: actions/cache@v3
        with:
          path: '~/.cache'
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run Cypress component tests
        run: yarn --cwd frontend test
