name: Cypress
on:
  pull_request:
    branches: [master, develop]

env:
  REGISTRY: ghcr.io

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend repository
      uses: actions/checkout@v2

    - name: Checkout frontend repository
      uses: actions/checkout@v2
      with:
        repository: echo-webkom/echo-web-frontend
        path: frontend

    - name: Login to Github Container Registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build backend with cache
      run: |
        docker build \
          --cache-from "$REGISTRY/$GITHUB_REPOSITORY:$TAG" \
          -t "$REGISTRY/$GITHUB_REPOSITORY:$TAG" \
          -t "$REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
        docker push "$REGISTRY/$GITHUB_REPOSITORY" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        REGISTRY: ${{ env.REGISTRY }}
        TAG: "${{ github.base_ref == 'master' && 'latest-prod' || 'latest-dev' }}"

    - name: Build frontend with cache
      run: |
        docker build \
          --cache-from "$REGISTRY/$FRONTEND_REPOSITORY:$TAG" \
          -t "$REGISTRY/$FRONTEND_REPOSITORY:$TAG" \
          -t "$REGISTRY/$FRONTEND_REPOSITORY:$GITHUB_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          frontend
        docker push "$REGISTRY/$FRONTEND_REPOSITORY" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        REGISTRY: ${{ env.REGISTRY }}
        FRONTEND_REPOSITORY: echo-webkom/echo-web-frontend
        TAG: latest

    - name: Run Cypress end-to-end tests against frontend
      run: docker-compose -f $COMPOSE_FILE up --exit-code-from=frontend
      env:
        REGISTRY: ${{ env.REGISTRY }}
        SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
        SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
        ADMIN_KEY: admin-passord
        COMPOSE_FILE: docker-compose.ci.yaml
