name: Destroy backend preview
on:
  pull_request:
    branches: [master]
    types: [closed]

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}'

jobs:
  destroy_backend_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Set environment variables
        id: env_vars
        run: |
          echo "BRANCH_NAME_FORMATTED=$(echo "$BRANCH_NAME" | sed -e 's/-*login-*//g' -e 's/renovate\/backend-//g' -e 's/[\/_\.]/-/g')" >> $GITHUB_OUTPUT
          echo "BACKEND_TAG=$BACKEND_TAG" >> $GITHUB_OUTPUT
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          BACKEND_TAG: ${{ steps.changed-files.outputs.any_changed == 'true' && github.sha || 'latest' }}

      - name: Destroy preview container
        run: |
          cd terraform/preview
          terraform init
          terraform workspace select $WORKSPACE_NAME && \
            terraform destroy -auto-approve -lock-timeout=15m && \
            terraform workspace select default && \
            terraform workspace delete $WORKSPACE_NAME
        env:
          TF_VAR_resource_group_name: 'echo-web-${{ steps.env_vars.outputs.BRANCH_NAME_FORMATTED }}'
          TF_VAR_location: norwayeast
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
          TF_VAR_backend_image: '$IMAGE_NAME/backend:$BACKEND_TAG'
          TF_VAR_admin_key: ${{ secrets.ADMIN_KEY_DEV }}
          TF_VAR_auth_secret: ${{ secrets.AUTH_SECRET }}
          TF_VAR_environment: preview
          ARM_CLIENT_ID: 225cb793-e592-482e-8612-2318bd5e0a6c
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: f16e6916-1e71-42a0-9df3-0246b805f432
          ARM_TENANT_ID: 10086e44-d4c5-4039-ab23-dc49610f7879
          WORKSPACE_NAME: ${{ steps.env_vars.outputs.BRANCH_NAME_FORMATTED }}
