name: Jest
on:
  pull_request:
    branches: [master]

jobs:
  jest_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --ignore-scripts

      - name: Run API & component tests
        run: |
          cd frontend
          yarn test
