name: Kotest

on:
  pull_request:
    branches: [develop, master]

jobs:
  kotest_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build backend with cache
      run: |
        docker build \
          --cache-from "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$TAG" \
          -t "$USERNAME/$IMAGE_NAME:$COMMIT_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
        docker push "$USERNAME/$IMAGE_NAME" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        IMAGE_NAME: echo-web-backend
        TAG: "${{ github.head_ref == 'refs/heads/develop' && 'latest-dev' || 'latest-prod' }}"
        COMMIT_SHA: ${{ github.sha }}

    - name: Run Kotest tests with Docker Compose
      run: ./scripts/test -t kotest
