name: Kotest

on:
  pull_request:
    branches: [develop, master]

jobs:
  kotest_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Kotest tests with Docker Compose
      run: ./scripts/test -t kotest
