name: Kotest

on:
  pull_request:
    branches: [develop, master]

env:
  REGISTRY: ghcr.io

jobs:
  kotest_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build backend with cache
      run: |
        docker build \
          --cache-from "$REGISTRY/$GITHUB_REPOSITORY" \
          -t "$REGISTRY/$GITHUB_REPOSITORY:$TAG" \
          -t "$REGISTRY/$GITHUB_REPOSITORY:$GITHUB_SHA" \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          .
        docker push "$REGISTRY/$GITHUB_REPOSITORY" --all-tags
      env:
        DOCKER_BUILDKIT: 1
        REGISTRY: ${{ env.REGISTRY }}
        TAG: "${{ github.head_ref == 'refs/heads/develop' && 'latest-dev' || 'latest-prod' }}"

    - name: Run Kotest tests with Docker Compose
      run: ./scripts/test -t kotest
