name: ktlint

on:
  pull_request:
    branches: [develop, master]

jobs:
  ktlint_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 13
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'

      - name: Run ktlint checks
        run: |
          ./gradlew loadKtlintReporters
          # For *.kts files
          ./gradlew runKtlintCheckOverKotlinScripts
          ./gradlew ktlintKotlinScriptCheck
          # For *.kt files in /src/main
          ./gradlew runKtlintCheckOverMainSourceSet
          ./gradlew ktlintMainSourceSetCheck
          # For *.kt files in /src/test
          ./gradlew runKtlintCheckOverTestSourceSet
          ./gradlew ktlintTestSourceSetCheck
