name: ktlint
on:
  pull_request:
    branches: [master]
    paths-ignore: ['backend/**']

jobs:
  ktlint_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
