name: ktlint
on:
  pull_request:
    branches: [master]
  merge_group:
    types: [checks_requested]

jobs:
  ktlint_checks:
    name: 'ktlint checks'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Run ktlint checks
        run: |
          cd backend
          ./gradlew loadKtlintReporters
          # For *.kts files
          ./gradlew runKtlintCheckOverKotlinScripts
          ./gradlew ktlintKotlinScriptCheck
          # For *.kt files in /src/main
          ./gradlew runKtlintCheckOverMainSourceSet
          ./gradlew ktlintMainSourceSetCheck
          # For *.kt files in /src/test
          ./gradlew runKtlintCheckOverTestSourceSet
          ./gradlew ktlintTestSourceSetCheck
