name: Lint & format
on:
  pull_request:
    branches: [master]
    paths-ignore: ['cms/**', 'frontend/**', '**/node_modules/**', 'yarn.lock']
  merge_group: [checks_requested]

jobs:
  lint_format:
    name: 'Lint & format'
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
