name: Check SQL migration syntax
on:
  pull_request:
    branches: [master]
    paths: ['backend/src/main/resources/db/migration/**']
  merge_group:
    types: [checks_requested]

jobs:
  psql_check:
    name: 'Check SQL migration syntax'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create temporary requirements.txt
        run: echo "pgsanity" > requirements.txt

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install PgSanity & dependencies
        run: |
          pip install -r requirements.txt
          sudo apt-get -y install libecpg-dev

      - name: Run PgSanity
        run: |
          cd backend/src/main/resources/db/migration
          find -name '*.sql' | xargs pgsanity
