name: Terraform format
on:
  pull_request:
    branches: [master]
    paths: ['terraform/**']

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check format
        run: |
          cd terraform
          terraform fmt -diff
