name: Terraform format & plan

on:
  pull_request:
    branches: [master]
    paths-ignore: ['terraform/**']
  merge_group:
    types: [checks_requested]

jobs:
  terraform_format:
    name: 'Terraform format'
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'

  terraform_plan:
    name: 'Terraform plan'
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
