name: Terraform format & plan
on:
  pull_request:
    branches: [master]
    paths: ['terraform/**']

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}'
  TF_VAR_db_password_dev: ${{ secrets.DB_PASSWORD_DEV }}
  TF_VAR_db_password_prod: ${{ secrets.DB_PASSWORD_PROD }}
  TF_VAR_admin_key_dev: ${{ secrets.ADMIN_KEY_DEV }}
  TF_VAR_admin_key_prod: ${{ secrets.ADMIN_KEY_PROD }}
  TF_VAR_auth_secret: ${{ secrets.AUTH_SECRET }}
  ARM_CLIENT_ID: 225cb793-e592-482e-8612-2318bd5e0a6c
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: f16e6916-1e71-42a0-9df3-0246b805f432
  ARM_TENANT_ID: 10086e44-d4c5-4039-ab23-dc49610f7879

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Check format
        run: |
          cd terraform
          terraform fmt -check -recursive

  terraform_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Plan main configuration
        run: |
          cd terraform/main
          terraform init
          terraform plan -lock-timeout=15m
