name: Terraform format
on:
  pull_request:
    branches: [master]
    paths-ignore: ['terraform/**']

jobs:
  terraform_format:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: echo 'Nothing to be done, passing checks.'
