name: Undeploy preview
on:
  pull_request:
    branches: [master]
    types: [closed]

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}'

jobs:
  undeploy_backend_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Set environment variables
        id: env_vars
        run: |
          echo "BRANCH_NAME_FORMATTED=$(echo "$BRANCH_NAME" | sed -e 's/[\/_]/-/g')" >> $GITHUB_OUTPUT
          echo "BACKEND_TAG=$BACKEND_TAG" >> $GITHUB_OUTPUT
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          BACKEND_TAG: ${{ steps.changed-files.outputs.any_changed == 'true' && github.sha || 'latest' }}

      - name: Undeploy preview container
        run: |
          cd terraform/preview
          terraform init
          terraform workspace select $WORKSPACE_NAME && \
            terraform destroy -auto-approve && \
            terraform workspace delete $WORKSPACE_NAME
        env:
          TF_VAR_resource_group_name: 'echo-web-${{ steps.env_vars.outputs.BRANCH_NAME_FORMATTED }}'
          TF_VAR_location: norwayeast
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_DEV }}
          TF_VAR_backend_image: '$IMAGE_NAME/backend:$BACKEND_TAG'
          TF_VAR_admin_key: ${{ secrets.ADMIN_KEY_DEV }}
          ARM_CLIENT_ID: c320aed0-41eb-4089-aedb-8a4ece92c3b5
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: 8afc7368-510a-404a-b4dd-c7351977b037
          ARM_TENANT_ID: 10086e44-d4c5-4039-ab23-dc49610f7879
          WORKSPACE_NAME: ${{ steps.env_vars.outputs.BRANCH_NAME_FORMATTED }}
